version: '3.8'

services:
  redis:
    image: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  frontend:
    image: ex29-frontend
    build: ./example-frontend/.
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:80 # backend is now using proxy server with port 80

  backend:
    image: ex29-backend
    build: ./example-backend/.
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
      - REQUEST_ORIGIN=http://localhost # backend is now accessed through http://localhost

    depends_on:
      - redis
      - db
    container_name: backend

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend



