FROM python:3.9 AS builder

WORKDIR /usr/src/app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry install

FROM python:3.9-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY . .

CMD ["python3", "src/main.py"]

# after: 113MB ---- 1.13GB -> 113MB

