FROM node:16.20.1-alpine AS builder

WORKDIR /usr/src/app

COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=builder /usr/src/app/build .

EXPOSE 80

# before: 128MB
# after: 50.9MB
