version: '3.8'

services:
  redis:
    image: redis
    container_name: redis

  frontend:
    image: ex23-frontend
    ports:
      - 5001:5001
    container_name: frontend

  backend:
    image: ex23-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: backend
