FROM golang:1.16-alpine AS builder

WORKDIR /usr/src/app

COPY . .

RUN go build

FROM alpine:latest

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .

EXPOSE 8080

CMD ./server

# before: 476MB
# after: 24.9MB
